/**
 * Generates the `sw.js` source text written into a consumer site's build
 * output by {@link serviceWorkerIntegration}. Modeled on oxpulse-chat's
 * production service worker (web/static/sw.js) — install/activate/cache
 * lifecycle only, stripped of push notifications and the app's per-room
 * force-navigate exception list, since a landing page has no live-call
 * state to protect.
 *
 * Comment text INSIDE the returned string ships as literal bytes in every
 * consumer's `dist/sw.js` — keep it brand-neutral (no project names), it is
 * not kit-repo-private the way this file's own doc comments are.
 */
export function generateServiceWorkerSource(cacheName: string): string {
  return `// Auto-generated by the build's service-worker integration.
// Do not edit by hand — regenerated on every build with a fresh cache name.
const CACHE = ${JSON.stringify(cacheName)};

self.addEventListener('install', () => {
  // No in-page state to protect on a landing site (unlike a chat/call app
  // that needs to warn before dropping a live session) — activate the new
  // worker immediately instead of waiting for all tabs to close.
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      // Drop every cache that isn't this build's — a version bump is a
      // full cache invalidation, no stale entry survives a deploy.
      const keys = await caches.keys();
      await Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key)));

      await self.clients.claim();

      // Force every open tab onto the fresh deploy. Ported from the
      // upstream chat-app SW pattern's activate handler: without this,
      // a tab left open across a deploy keeps serving whatever the old
      // worker cached until the user manually reloads. A landing page has
      // no per-tab session to lose, so unlike that pattern this reloads
      // every window client unconditionally — no route is exempted.
      const clients = await self.clients.matchAll({ type: 'window' });
      for (const client of clients) {
        client.navigate(client.url).catch(() => {});
      }
    })()
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  // Never intercept cross-origin requests (widgets, APIs, third-party
  // embeds) — only this origin's own responses are safe to cache.
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    // Network-first for page navigations: always serve the latest HTML
    // when online, fall back to whatever got cached last time offline.
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy));
          return response;
        })
        .catch(() => caches.match(request).then((cached) => cached ?? caches.match('/')))
    );
    return;
  }

  if (url.pathname.startsWith('/_astro/')) {
    // Astro's build output hashes these filenames by content — an entry
    // never goes stale, so cache-first with a background refill is safe
    // and skips the network entirely on a warm cache.
    event.respondWith(
      caches.match(request).then(
        (cached) =>
          cached ??
          fetch(request).then((response) => {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy));
            return response;
          })
      )
    );
    return;
  }

  // Everything else: no event.respondWith() call — falls through to the
  // browser's default fetch, untouched by this worker.
});
`;
}
